
package org.cn.kkl.ws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.cn.kkl.ws.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWeatherService", targetNamespace = "http://ws.kkl.cn.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWeatherService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "info", targetNamespace = "http://ws.kkl.cn.org/", className = "org.cn.kkl.ws.Info")
    @ResponseWrapper(localName = "infoResponse", targetNamespace = "http://ws.kkl.cn.org/", className = "org.cn.kkl.ws.InfoResponse")
    public String info(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
